language: node_js
node_js:
- '9'
sudo: required
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
- npm install -g typescript@5.18.0 && tsc -v
- npm install -g tslint@3.7.5
install:
- npm install
script:
- npm run lint
- npm run build:lnx
